### ISSUE TITLE
ValueError: insecure string pickle

### ISSUE THREAD

**Issue by phretor** [markokr/rarfile#16]
On Mac OS X El Capitan

```python
$ python --version
Python 2.7.10
$ git clone https://github.com/markokr/rarfile.git
$ cd rarfile
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import rarfile
  File "/Users/phretor/reversing/tools/aleph/rarfile/rarfile.py", line 1973, in <module>
    custom_check([UNRAR_TOOL], True)
  File "/Users/phretor/reversing/tools/aleph/rarfile/rarfile.py", line 1921, in custom_check
    p = custom_popen(cmd)
  File "/Users/phretor/reversing/tools/aleph/rarfile/rarfile.py", line 1911, in custom_popen
    creationflags = creationflags)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by markokr** [comment]
Looks like warning about pickle usage in subprocess module.  Data corruption?  Bug in pickle or subprocess?

Can't see how rarfile can do anything to avoid it.

If this is reproducible, it might be good to report it to Python devs.

**Comment by phretor** [comment]
It's due to how the missing unrar executable is (mis)handled by
subprocess.Popen. This raises a ValueError that is apparently not handled
by subprocess.Popen, which should raise an os error (that rarfile properly
catch).

As far as rarfile is concerned, maybe a note in the doc that the unrar
executable is required.
