### ISSUE TITLE
rarfile's custom_check/custom_popen doesn't handle permission issues

### ISSUE THREAD

**Issue by pannal** [markokr/rarfile#38]
In this example a user tried to import rarfile on an NVIDIA SHIELD platform.
The SHIELD has very limited permissions (SELinux enforced) when the user hasn't rooted the device, resulting in:

```
Traceback (most recent call last):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/__init__.py", line 17, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/core.py", line 14, in <module>
    from rarfile import NotRarFile, RarCannotExec, RarFile
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by Dobatymo** [comment]
was fixed here https://github.com/markokr/rarfile/commit/84ca97e5547963daf89690e7457fd861407c292f

**Comment by markokr** [comment]
I guess I can close this.
