### ISSUE TITLE
nested exception RAR archive with encrypt filename

### ISSUE THREAD

**Issue by peondusud** [markokr/rarfile#64]
```
 RuntimeError <class 'RuntimeError'> Archive is encrypted, password required apps2.rar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/unrar/rarfile.py", line 153, in _read_header
    res = unrarlib.RARReadHeaderEx(handle, ctypes.byref(header_data))
  File "/usr/local/lib/python3.7/dist-packages/unrar/unrarlib.py", line 243, in _check_readheader_result
    raise MissingPassword("Password missing")
unrar.unrarlib.MissingPassword: Password missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 40, in get_RarFile
    return rarfile.RarFile(p)
  File "/usr/local/lib/python3.7/dist-packages/unrar/rarfile.py", line 140, in __init__
    self._load_metadata(handle)
  File "/usr/local/lib/python3.7/dist-packages/unrar/rarfile.py", line 172, in _load_metadata
    rarinfo = self._read_header(handle)
  File "/usr/local/lib/python3.7/dist-packages/unrar/rarfile.py", line 158, in _read_header
    raise RuntimeError("Archive is encrypted, password required")
RuntimeError: Archive is encrypted, password required
```

**apps2.rar is a RAR archive with encrypt filename**

My code
```
def get_RarFile(path_obj):
    p = str(path_obj.absolute())
    if rarfile.is_rarfile(p):
        try:
            return rarfile.RarFile(p)
        except (MissingPassword, RuntimeError, UnrarException) as e:
            logger.exception("RuntimeError {} {} {}".format(type(e), str(e), p))
        except Exception as e:
            logger.exception("Exception {} {} {}".format(type(e), str(e), p))

```

ref:
https://stackoverflow.com/questions/52725278/during-handling-of-the-above-exception-another-exception-occurred

**Comment by markokr** [comment]
Stacktrace shows - `dist-packages/unrar` - that you are not using this module but one of the other RAR modules.  Probably this one - https://pypi.org/project/unrar/

Please report problem to their issue tracker.

**Comment by peondusud** [comment]
Hi,
Yes you re right
```
from unrar import rarfile
from unrar.unrarlib import MissingPassword, UnrarException
```
I'm so confused I use your docs on their module.
Seems weird same function name, exception, etc
