### ISSUE TITLE
Invalid syntax Error while importing Rarfile in python 3.5 and 2.7 in ubuntu 16.04

### ISSUE THREAD

**Issue by fizzafaroooq** [markokr/rarfile#66]
I am getting this weird invalid syntax error while importing rarfile in python 3.5 and python 2.7

I have already installed rarfile using 'pip install rarfile' command to install it with python 3.5(default).
I have installed rarfile using 'python2.7 -m pip install rarfile' command to install it in python 2.7.
I am using ubuntu 16.04.

**$ pip install rarfile**

outpout:

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: rarfile in /home/fizza/.local/lib/python3.5/site-packages (4.0)

**$ python**

Output:

Python 3.5.2 (default, Jul 17 2020, 14:04:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import rarfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fizza/.local/lib/python3.5/site-packages/rarfile.py", line 946
    warnings.warn(f"Windows junction not supported - {info.filename}", UnsupportedWarning)
                                                                    ^
SyntaxError: invalid syntax

**For Python 2.7**

**$ python2.7 -m pip install rarfile**

output: 

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rarfile in /home/fizza/.local/lib/python2.7/site-packages (4.0)

**$ python2.7**

Python 2.7.12 (default, Jul 21 2020, 15:19:50) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import rarfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fizza/.local/lib/python2.7/site-packages/rarfile.py", line 811
    print(f.filename, file=file)
                          ^
SyntaxError: invalid syntax

**Comment by fizzafaroooq** [comment]
My bad, it is mentioned in documentation, rarfile is supported for python 3.6+
Closing the issue.
