### ISSUE TITLE
Cannot extract anything from a encrypted rar

### ISSUE THREAD

**Issue by IAXRetailer** [markokr/rarfile#87]
### Platform

- python 3.8.10
- rarfile 4.0
- Windows 7

### Code
```
from rarfile import RarFile
with RarFile("test1.rar") as f:
    for name in f.namelist():
        f.extract(name,"","123".encode("utf-8"))
```
### Log
```
Traceback (most recent call last):
  File "F:\rpcpost\SaltZip-QT\test\test.py", line 5, in <module>
    f.extract(name,"","123".encode("utf-8"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\rarfile.py", line 826, in extract
    return self._extract_one(inf, path, pwd, True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\rarfile.py", line 927, in _make_file
    shutil.copyfileobj(src, dst)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=9 got=0
```
I also try to extract a unencrypted file,but it seems anything fine.(I also put unrar.exe in the code folder)

### Download

https://cdn.xhacgn.com/api/v3/slave/source/0/dXBsb2Fkcy8xMC8yMDIyLzA3LzE4LzhYUGhoZ0Z2X3Rlc3QudGFy/test.tar?sign=aqFSiLus2bLHGwzz8MKipt4pxcgp-j35Zx4A_Y55StE%3D%3A0

**Comment by IAXRetailer** [comment]
I have already solved it by upgrading the UnRar.exe
